title: "LogMaks Journal"
description: "Scientific blog, notes and projects"
url: "https://logmaks.github.io"
baseurl: ""

# GitHub Pages совместимые плагины
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
permalink: /posts/:title/
timezone: UTC
lang: en

author:
  name: "LogMaks"
  email: ""
  url: "/about/"

collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "LogMaks"
      image: ""
  - scope:
      path: ""
      type: "projects"
    values:
      layout: post
      author: "LogMaks"
      image: ""

sass:
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

